rig_id: l4_all_up_20cm
vehicle_frame:
  convention: x_forward_y_left_z_up
  source_frame: ego
cameras:
  - name: CAM_BACK
    model: pinhole_brown
    width: 1920
    height: 1080
    inherit_source_camera: CAM_BACK
    vehicle_offset_m: [0.0, 0.0, 0.20]
    T_camera_from_vehicle: identity
  - name: CAM_BACK_LEFT
    model: pinhole_brown
    width: 1920
    height: 1080
    inherit_source_camera: CAM_BACK_LEFT
    vehicle_offset_m: [0.0, 0.0, 0.20]
    T_camera_from_vehicle: identity
  - name: CAM_BACK_RIGHT
    model: pinhole_brown
    width: 1920
    height: 1080
    inherit_source_camera: CAM_BACK_RIGHT
    vehicle_offset_m: [0.0, 0.0, 0.20]
    T_camera_from_vehicle: identity
  - name: CAM_FRONT_LEFT
    model: pinhole_brown
    width: 1920
    height: 1080
    inherit_source_camera: CAM_FRONT_LEFT
    vehicle_offset_m: [0.0, 0.0, 0.20]
    T_camera_from_vehicle: identity
  - name: CAM_FRONT_NARROW
    model: pinhole_brown
    width: 1920
    height: 1080
    inherit_source_camera: CAM_FRONT_NARROW
    vehicle_offset_m: [0.0, 0.0, 0.20]
    T_camera_from_vehicle: identity
  - name: CAM_FRONT_RIGHT
    model: pinhole_brown
    width: 1920
    height: 1080
    inherit_source_camera: CAM_FRONT_RIGHT
    vehicle_offset_m: [0.0, 0.0, 0.20]
    T_camera_from_vehicle: identity
  - name: CAM_FRONT_WIDE
    model: pinhole_brown
    width: 1920
    height: 1080
    inherit_source_camera: CAM_FRONT_WIDE
    vehicle_offset_m: [0.0, 0.0, 0.20]
    T_camera_from_vehicle: identity
