"""Render real multi-camera sequences as timestamp-aware 30 FPS MP4 videos.

Real images are retained as temporal anchors. Between two anchors, frames are
generated by motion-compensated interpolation. The legacy linear blend remains
available as a baseline; neither method creates new metric LiDAR truth.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

import cv2
import numpy as np

import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from gcr_nvs.datasets.manifest import CAMERA_NAMES, build_sequence_manifest, sensor_timestamp


def _read(path: Path, size: tuple[int, int] | None) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise RuntimeError(f"failed to decode {path}")
    if size is not None and (image.shape[1], image.shape[0]) != size:
        image = cv2.resize(image, size, interpolation=cv2.INTER_AREA)
    return image


def _writer(path: Path, size: tuple[int, int], fps: float) -> cv2.VideoWriter:
    path.parent.mkdir(parents=True, exist_ok=True)
    for codec in ("avc1", "mp4v"):
        writer = cv2.VideoWriter(str(path), cv2.VideoWriter_fourcc(*codec), fps, size)
        if writer.isOpened():
            return writer
    raise RuntimeError(f"could not open MP4 writer for {path}")


def _fps_tag(fps: float) -> str:
    value = float(fps)
    return f"{int(round(value))}fps" if value.is_integer() else f"{value:g}fps"


def _flow_interpolator(preset: str = "fast"):
    if not hasattr(cv2, "DISOpticalFlow_create"):
        return None
    presets = {
        "ultrafast": cv2.DISOPTICAL_FLOW_PRESET_ULTRAFAST,
        "fast": cv2.DISOPTICAL_FLOW_PRESET_FAST,
        "medium": cv2.DISOPTICAL_FLOW_PRESET_MEDIUM,
    }
    if preset not in presets:
        raise ValueError(f"unknown DIS preset {preset!r}")
    flow = cv2.DISOpticalFlow_create(presets[preset])
    # Keep the interpolation practical at 960x540 while retaining the
    # variational refinement that reduces blocky motion around object edges.
    flow.setVariationalRefinementIterations(1)
    return flow


def _warp(image: np.ndarray, flow: np.ndarray, scale: float) -> tuple[np.ndarray, np.ndarray]:
    height, width = image.shape[:2]
    yy, xx = np.mgrid[0:height, 0:width].astype(np.float32)
    map_x = xx - scale * flow[..., 0]
    map_y = yy - scale * flow[..., 1]
    valid = (map_x >= 0) & (map_x <= width - 1) & (map_y >= 0) & (map_y <= height - 1)
    warped = cv2.remap(image, map_x, map_y, cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)
    return warped, valid


def _flow_consistency(flow_forward: np.ndarray, flow_backward: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return source/target forward-backward consistency confidence maps."""
    height, width = flow_forward.shape[:2]
    yy, xx = np.mgrid[0:height, 0:width].astype(np.float32)
    # Reverse flow sampled at the forward-mapped position.
    reverse_at_target = cv2.remap(
        flow_backward,
        xx + flow_forward[..., 0],
        yy + flow_forward[..., 1],
        cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_REPLICATE,
    )
    error_forward = np.linalg.norm(flow_forward + reverse_at_target, axis=-1)
    forward_at_source = cv2.remap(
        flow_forward,
        xx + flow_backward[..., 0],
        yy + flow_backward[..., 1],
        cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_REPLICATE,
    )
    error_backward = np.linalg.norm(flow_backward + forward_at_source, axis=-1)
    return error_forward, error_backward


def _motion_interpolate(
    left: np.ndarray,
    right: np.ndarray,
    alpha: float,
    flow_engine,
    fb_sigma: float = 1.5,
    disagreement: float = 28.0,
    flow_pair: tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray] | None = None,
) -> tuple[np.ndarray, dict]:
    """Bidirectional flow warp with occlusion-aware confidence blending."""
    if flow_engine is None:
        return cv2.addWeighted(left, 1.0 - alpha, right, alpha, 0.0), {"fallback": True}
    if flow_pair is None:
        gray_left = cv2.cvtColor(left, cv2.COLOR_BGR2GRAY)
        gray_right = cv2.cvtColor(right, cv2.COLOR_BGR2GRAY)
        flow_forward = flow_engine.calc(gray_left, gray_right, None)
        flow_backward = flow_engine.calc(gray_right, gray_left, None)
        error_left, error_right = _flow_consistency(flow_forward, flow_backward)
    else:
        flow_forward, flow_backward, error_left, error_right = flow_pair
    warped_left, valid_left = _warp(left, flow_forward, alpha)
    warped_right, valid_right = _warp(right, flow_backward, 1.0 - alpha)

    consistency_left = np.exp(-np.clip(error_left, 0.0, 40.0) / max(fb_sigma, 1e-3))
    consistency_right = np.exp(-np.clip(error_right, 0.0, 40.0) / max(fb_sigma, 1e-3))
    # Compare aligned colors. Large disagreement is usually an occlusion or
    # a flow failure; selecting the temporally nearer endpoint avoids a double
    # contour, while normal regions retain a smooth weighted blend.
    color_delta = np.linalg.norm(warped_left.astype(np.float32) - warped_right.astype(np.float32), axis=-1)
    temporal_left = (1.0 - alpha) * consistency_left * valid_left
    temporal_right = alpha * consistency_right * valid_right
    total = temporal_left + temporal_right
    output = (
        warped_left.astype(np.float32) * temporal_left[..., None]
        + warped_right.astype(np.float32) * temporal_right[..., None]
    ) / np.maximum(total[..., None], 1e-6)
    hard_conflict = color_delta > float(disagreement)
    prefer_left = consistency_left >= consistency_right
    choose_left = hard_conflict & (prefer_left | (alpha < 0.5))
    choose_right = hard_conflict & ~choose_left
    output[choose_left] = warped_left[choose_left]
    output[choose_right] = warped_right[choose_right]
    missing = total <= 1e-6
    output[missing] = left[missing] if alpha < 0.5 else right[missing]
    return np.uint8(np.clip(output, 0, 255)), {
        "fallback": False,
        "flow_conflict_fraction": float(hard_conflict.mean()),
        "flow_invalid_fraction": float(missing.mean()),
    }


def render_sequence(
    sequence: Path,
    output: Path,
    fps: float,
    size: tuple[int, int] | None,
    cameras: list[str],
    method: str = "flow",
    dis_preset: str = "fast",
    flow_disagreement: float = 28.0,
) -> dict:
    records = build_sequence_manifest(sequence, compute_quality=False)
    if len(records) < 2:
        raise ValueError("sequence must contain at least two frames")
    if size is None:
        first_path = sequence / records[0].cameras[cameras[0]]
        first = _read(first_path, None)
        size = (first.shape[1], first.shape[0])

    if method not in {"flow", "linear"}:
        raise ValueError("method must be 'flow' or 'linear'")
    flow_engines = {camera: _flow_interpolator(dis_preset) for camera in cameras} if method == "flow" else {}
    tag = _fps_tag(fps)
    writers = {camera: _writer(output / f"{camera}_{tag}.mp4", size, fps) for camera in cameras}
    frame_count = 0
    conflict_values: list[float] = []
    fallback_count = 0
    try:
        for index in range(len(records) - 1):
            left, right = records[index], records[index + 1]
            dt = sensor_timestamp(right) - sensor_timestamp(left)
            if dt <= 0:
                raise ValueError(f"non-increasing timestamp at {left.frame_id}->{right.frame_id}")
            slices = max(1, int(round(dt * fps)))
            left_images = {
                camera: _read(sequence / left.cameras[camera], size) for camera in cameras
            }
            right_images = {
                camera: _read(sequence / right.cameras[camera], size) for camera in cameras
            }
            flow_pairs = {}
            if method == "flow":
                for camera in cameras:
                    engine = flow_engines[camera]
                    if engine is None:
                        flow_pairs[camera] = None
                    else:
                        gray_left = cv2.cvtColor(left_images[camera], cv2.COLOR_BGR2GRAY)
                        gray_right = cv2.cvtColor(right_images[camera], cv2.COLOR_BGR2GRAY)
                        forward = engine.calc(gray_left, gray_right, None)
                        backward = engine.calc(gray_right, gray_left, None)
                        error_left, error_right = _flow_consistency(forward, backward)
                        flow_pairs[camera] = (forward, backward, error_left, error_right)
            if index == 0:
                for camera in cameras:
                    writers[camera].write(left_images[camera])
                frame_count += 1
            for step in range(1, slices):
                alpha = step / slices
                for camera in cameras:
                    if method == "flow":
                        blended, flow_report = _motion_interpolate(
                            left_images[camera], right_images[camera], alpha,
                            flow_engines[camera], disagreement=flow_disagreement,
                            flow_pair=flow_pairs.get(camera),
                        )
                        if flow_report.get("fallback"):
                            fallback_count += 1
                        elif "flow_conflict_fraction" in flow_report:
                            conflict_values.append(flow_report["flow_conflict_fraction"])
                    else:
                        blended = cv2.addWeighted(left_images[camera], 1.0 - alpha, right_images[camera], alpha, 0.0)
                    writers[camera].write(blended)
                frame_count += 1
            for camera in cameras:
                writers[camera].write(right_images[camera])
            frame_count += 1
    finally:
        for writer in writers.values():
            writer.release()

    report = {
        "sequence_id": sequence.name,
        "output": str(output),
        "cameras": cameras,
        "fps": fps,
        "resolution": [size[0], size[1]],
        "real_frames": len(records),
        "output_frames": frame_count,
        "duration_s": (frame_count - 1) / fps,
        "method": "timestamp-aware bidirectional DIS optical-flow interpolation with real-frame anchors" if method == "flow" else "timestamp-aware linear RGB interpolation with real-frame anchors",
        "flow_preset": dis_preset if method == "flow" else None,
        "flow_disagreement_threshold": flow_disagreement if method == "flow" else None,
        "mean_flow_conflict_fraction": float(np.mean(conflict_values)) if conflict_values else 0.0,
        "flow_fallback_intermediate_frames": fallback_count,
        "metric_lidar_policy": "real LiDAR remains attached only to real anchors; intermediate frames have no synthetic LiDAR GT",
    }
    output.mkdir(parents=True, exist_ok=True)
    (output / "render_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report


def make_contact_video(output: Path, cameras: list[str], fps: float, size: tuple[int, int]) -> Path:
    tag = _fps_tag(fps)
    paths = [output / f"{camera}_{tag}.mp4" for camera in cameras]
    readers = [cv2.VideoCapture(str(path)) for path in paths]
    grid_size = (size[0] * 2, size[1] * 4)
    path = output / f"seven_view_{tag}.mp4"
    writer = _writer(path, grid_size, fps)
    try:
        while True:
            frames = []
            for reader in readers:
                ok, frame = reader.read()
                if not ok:
                    return path
                frames.append(frame)
            blank = np.zeros_like(frames[0])
            rows = []
            for start in range(0, len(frames), 2):
                row = frames[start:start + 2]
                if len(row) == 1:
                    row.append(blank.copy())
                rows.append(np.concatenate(row, axis=1))
            writer.write(np.concatenate(rows, axis=0))
    finally:
        writer.release()
        for reader in readers:
            reader.release()


def render_sequence_ffmpeg_mci(
    sequence: Path,
    output: Path,
    fps: float,
    size: tuple[int, int] | None,
    cameras: list[str],
) -> dict:
    """Use FFmpeg's motion-compensated interpolation on real anchor frames.

    Unlike the previous flow implementation, this passes only real anchors to
    ``minterpolate``. The filter performs its own bidirectional motion search
    and occlusion-aware block compensation, so a previously blended frame can
    never become an input and accumulate a double contour.
    """
    records = build_sequence_manifest(sequence, compute_quality=False)
    if len(records) < 2:
        raise ValueError("sequence must contain at least two frames")
    if size is None:
        first = _read(sequence / records[0].cameras[cameras[0]], None)
        size = (first.shape[1], first.shape[0])
    output.mkdir(parents=True, exist_ok=True)
    duration = sensor_timestamp(records[-1]) - sensor_timestamp(records[0])
    expected_frames = int(round(duration * fps)) + 1
    temp_root = Path(tempfile.mkdtemp(prefix="gcr_nvs_mci_", dir=str(output.parent)))
    try:
        for camera in cameras:
            concat = temp_root / f"{camera}.txt"
            lines: list[str] = []
            for index, record in enumerate(records):
                image_path = (sequence / record.cameras[camera]).resolve()
                # FFmpeg concat duration applies to the preceding file. The
                # final duplicate keeps the last real frame until the end.
                lines.append(f"file '{image_path.as_posix()}'")
                if index < len(records) - 1:
                    dt = sensor_timestamp(records[index + 1]) - sensor_timestamp(record)
                    if dt <= 0:
                        raise ValueError(f"non-increasing timestamp at {record.frame_id}")
                    lines.append(f"duration {dt:.9f}")
            lines.append(f"file '{(sequence / records[-1].cameras[camera]).resolve().as_posix()}'")
            concat.write_text("\n".join(lines) + "\n", encoding="utf-8")
            anchor = temp_root / f"{camera}_anchors.mp4"
            final = output / f"{camera}_{_fps_tag(fps)}.mp4"
            scale = f"scale={size[0]}:{size[1]}:flags=lanczos,format=yuv420p"
            subprocess.run(
                ["ffmpeg", "-y", "-loglevel", "error", "-f", "concat", "-safe", "0", "-i", str(concat),
                 "-vf", scale, "-vsync", "vfr", "-c:v", "libx264", "-preset", "fast", "-crf", "17", str(anchor)],
                check=True,
            )
            # MCI + AOBMC + bidirectional search is substantially less prone
            # to the torn edges produced by independently warped RGB frames.
            subprocess.run(
                ["ffmpeg", "-y", "-loglevel", "error", "-i", str(anchor),
                 "-vf", f"minterpolate=fps={fps:g}:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1",
                 "-vsync", "cfr", "-c:v", "libx264", "-preset", "fast", "-crf", "17", str(final)],
                check=True,
            )
    finally:
        shutil.rmtree(temp_root, ignore_errors=True)

    report = {
        "sequence_id": sequence.name,
        "output": str(output),
        "cameras": cameras,
        "fps": fps,
        "resolution": [size[0], size[1]],
        "real_frames": len(records),
        "output_frames_expected": expected_frames,
        "duration_s": duration,
        "method": "FFmpeg minterpolate MCI with AOBMC/bidirectional motion search from real anchors",
        "anchor_policy": "only real RGB frames are passed to minterpolate",
        "metric_lidar_policy": "real LiDAR remains attached only to real anchors; intermediate frames have no synthetic LiDAR GT",
    }
    (output / "render_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("sequence", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--fps", type=float, default=30.0)
    parser.add_argument("--width", type=int, default=None)
    parser.add_argument("--height", type=int, default=None)
    parser.add_argument("--camera", action="append", choices=CAMERA_NAMES, default=None)
    parser.add_argument("--no-contact", action="store_true")
    parser.add_argument("--method", choices=("mci", "flow", "linear"), default="mci")
    parser.add_argument("--dis-preset", choices=("ultrafast", "fast", "medium"), default="fast")
    parser.add_argument("--flow-disagreement", type=float, default=28.0)
    args = parser.parse_args()
    cameras = args.camera or list(CAMERA_NAMES)
    size = None if args.width is None and args.height is None else (args.width, args.height)
    if size is not None and (size[0] is None or size[1] is None or size[0] <= 0 or size[1] <= 0):
        raise ValueError("width and height must both be positive")
    if args.method == "mci":
        report = render_sequence_ffmpeg_mci(args.sequence, args.output, args.fps, size, cameras)
    else:
        report = render_sequence(
            args.sequence, args.output, args.fps, size, cameras,
            method=args.method, dis_preset=args.dis_preset,
            flow_disagreement=args.flow_disagreement,
        )
    if not args.no_contact and cameras == list(CAMERA_NAMES):
        make_contact_video(args.output, cameras, args.fps, tuple(report["resolution"]))
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
